version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: ecommercedbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: 'http://3.72.75.83:8000'
    image: skudsi/ecommerce-django-react-web:latest
    container_name: web
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONPATH=/app:/app/backend:/app/base
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerceuser
      - POSTGRES_PASSWORD=ecommercedbpassword
      - POSTGRES_HOST=db
      - REACT_APP_BACKEND_URL=http://3.72.75.83:8000
    volumes:
      - /home/ubuntu/ecommerce-django-react/backend:/app/backend
      - /home/ubuntu/ecommerce-django-react/base:/app/base
      - /home/ubuntu/ecommerce-django-react/requirements.txt:/app/requirements.txt
      - /home/ubuntu/ecommerce-django-react/manage.py:/app/manage.py
      - /home/ubuntu/ecommerce-django-react/static:/app/static
      - /home/ubuntu/ecommerce-django-react/media:/app/media
      - /home/ubuntu/ecommerce-django-react/staticfiles:/app/staticfiles
      - /home/ubuntu/ecommerce-django-react/data_dump.json:/tmp/data_dump.json
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/ecommerce-django-react/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/ecommerce-django-react/ecommerce-django-react.conf:/etc/nginx/conf.d/ecommerce-django-react.conf:ro
      - /home/ubuntu/ecommerce-django-react/static:/usr/share/nginx/html/static
      - /home/ubuntu/ecommerce-django-react/media:/usr/share/nginx/html/media
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
