version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: ecommercedbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: skudsi/ecommerce-django-react-backend:latest
    container_name: backend
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONPATH=/app:/app/backend:/app/base
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerceuser
      - POSTGRES_PASSWORD=ecommercedbpassword
      - POSTGRES_HOST=db
    volumes:
      - ./backend:/app/backend
      - ./base:/app/base
      - ./requirements.txt:/app/requirements.txt
      - ./manage.py:/app/manage.py
      - ./static:/app/static
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./data_dump.json:/tmp/data_dump.json
    depends_on:
      - db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: skudsi/ecommerce-django-react-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/reports:/app/reports
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  frontend_build:

networks:
  app-network:
    driver: bridge
