version: '3'

services:
  backend:
    image: skudsi/ecommerce-django-react-backend:latest
    container_name: backend
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
    environment:
      - DEBUG=1
    volumes:
      - ./backend:/app/backend
      - ./requirements.txt:/app/requirements.txt  

  frontend:
    image: skudsi/ecommerce-django-react-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
